name: Angular Deployment

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'

      - name: Use Node.js version
        run: |
          node --version
          npm --version

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Install dependencies
        run: npm install
        working-directory: ./my-angular-app

      - name: Build Angular app
        run: ng build --configuration=production
        working-directory: ./my-angular-app

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Configure AWS credentials
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set default.region ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Create S3 bucket
        run: |
          aws s3api create-bucket --bucket angular-buck --region ap-south-1 --create-bucket-configuration LocationConstraint=ap-south-1


      - name: Deploy to AWS S3
        run: |
          aws s3 sync ./my-angular-app/src/ s3://angular-buck

      - name: Configure S3 bucket for static website hosting
        run: |
          aws s3 website s3://angular-buck --index-document index.html --error-document index.html

      - name: Set public read access for objects in the bucket
        run: |
          aws s3api put-bucket-policy --bucket angular-buck --policy '{
            {
              "Version": "2012-10-17",
              "Statement": [
              {
                 "Effect": "Allow",
                 "Action": "s3:PutBucketPolicy",
                 "Resource": "arn:aws:s3:::angular-buck"
              }
            ]
          }


          }'
